### ISSUE TITLE
[1.15.2] ArrayIndexOutOfBoundsExeption: 1099

### ISSUE THREAD

**Issue by replaceitem** [MamiyaOtaru/voxelmap#34]
The client crashes randomly, leaving me with this crashlog:

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/27/20 2:49 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 1099
	at com.mamiyaotaru.voxelmap.util.MapChunkCache.isChunkSurroundedByLoaded(MapChunkCache.java:141)
	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.isChunkReady(PersistentMap.java:1185)
	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.handleChangeInWorld(PersistentMap.java:1108)
	at com.mamiyaotaru.voxelmap.util.WorldUpdateListener.notifyObservers(WorldUpdateListener.java:47)
	at net.minecraft.class_761.handler$zil000$postScheduleChunkRender(class_761.java:5003)
	at net.minecraft.class_761.method_3295(class_761.java:2390)
	at net.minecraft.class_761.method_8571(class_761.java:2385)
	at net.minecraft.class_631.method_12247(class_631.java:174)
	at net.minecraft.class_3560.method_15530(class_3560.java:374)
	at net.minecraft.class_3558.method_15516(class_3558.java:203)
	at net.minecraft.class_3568.method_15563(class_3568.java:68)
	at net.minecraft.class_761.method_22710(class_761.java:1046)
	at net.minecraft.class_757.method_3188(class_757.java:718)
	at net.minecraft.class_757.method_3192(class_757.java:543)
	at net.minecraft.class_310.method_1523(class_310.java:989)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mamiyaotaru.voxelmap.util.MapChunkCache.isChunkSurroundedByLoaded(MapChunkCache.java:141)
	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.isChunkReady(PersistentMap.java:1185)
	at com.mamiyaotaru.voxelmap.persistent.PersistentMap.handleChangeInWorld(PersistentMap.java:1108)
	at com.mamiyaotaru.voxelmap.util.WorldUpdateListener.notifyObservers(WorldUpdateListener.java:47)
	at net.minecraft.class_761.handler$zil000$postScheduleChunkRender(class_761.java:5003)
	at net.minecraft.class_761.method_3295(class_761.java:2390)
	at net.minecraft.class_761.method_8571(class_761.java:2385)
	at net.minecraft.class_631.method_12247(class_631.java:174)
	at net.minecraft.class_3560.method_15530(class_3560.java:374)
	at net.minecraft.class_3558.method_15516(class_3558.java:203)
	at net.minecraft.class_3568.method_15563(class_3568.java:68)
	at net.minecraft.class_761.method_22710(class_761.java:1046)
	at net.minecraft.class_757.method_3188(class_757.java:718)

-- Affected level --
Details:
	All players: 2 total; [class_746['replaceitem'/480481, l='MpServer', x=-188.55, y=23.00, z=-83.08], class_745['Goldbear'/342535, l='MpServer', x=-1.34, y=0.50, z=159.69]]
	Chunk stats: Client Chunk Cache: 3025, 2573
	Level dimension: minecraft:the_nether
	Level name: MpServer
	Level seed: -6028445737087606203
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 47133474 game time, 46070689 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_252, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 803360392 bytes (766 MB) / 2856321024 bytes (2724 MB) up to 3773300736 bytes (3598 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4048m
	Fabric Mods: 
		authme: Auth Me 1.1.1
		carpet: Carpet Mod in Fabric 1.4.0
		dynamicfps: Dynamic FPS 1.0.4
		fabric: Fabric API 0.4.29+build.290-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.9+aea78a250c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.22+203491ea0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.8.8+build.202
		itemscroller: Item Scroller 0.15.0-dev.20200616.032713
		litematica: Litematica 0.0.0-dev.20200515.184506
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		minecraft: Minecraft 1.15.2
		minihud: MiniHUD 0.19.0-dev.20200508.032934
		modmenu: Mod Menu 1.10.2+build.32
		tweakeroo: Tweakeroo 0.10.0-dev.20200517.222522
		voxelmap: VoxelMap 1.9.18.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) R7 Graphics GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks_r288400.zip
	Current Language: English (US)
	CPU: 4x AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G
```

**Comment by replaceitem** [comment]
Update:
I found out it only happens when in the nether
