### ISSUE TITLE
Null Pointer Exception on Get Sky Color

### ISSUE THREAD

**Issue by BMK2** [MamiyaOtaru/voxelmap#36]
When I log in to a server I'm playing on that is backward compatible with older versions, I'm getting the following error:

```
java.lang.NullPointerException: null
	at net.optifine.CustomColors.getWorldSkyColor(CustomColors.java:1536) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_758.method_3210(class_758.java:91) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at com.mamiyaotaru.voxelmap.Map.getSkyColor(Map.java:991) ~[fabricmod_VoxelMap-1.10.6b_for_1.16.1.jar:?]
	at com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:962) ~[fabricmod_VoxelMap-1.10.6b_for_1.16.1.jar:?]
	at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:695) ~[fabricmod_VoxelMap-1.10.6b_for_1.16.1.jar:?]
	at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:195) ~[fabricmod_VoxelMap-1.10.6b_for_1.16.1.jar:?]
	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:74) ~[fabricmod_VoxelMap-1.10.6b_for_1.16.1.jar:?]
	at net.minecraft.class_329.handler$zgd000$onRenderGameOverlay(class_329.java:1811) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:441) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:750) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204.jar:?]
```

**Comment by BMK2** [comment]
Here is the entire crash report
```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/26/20 12:03 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.optifine.CustomColors.getWorldSkyColor(CustomColors.java:1536)
	at net.minecraft.class_758.method_3210(class_758.java:91)
	at com.mamiyaotaru.voxelmap.Map.getSkyColor(Map.java:991)
	at com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:962)
	at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:695)
	at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:195)
	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:74)
	at net.minecraft.class_329.handler$zgd000$onRenderGameOverlay(class_329.java:1811)
	at net.minecraft.class_329.method_1753(class_329.java:441)
	at net.minecraft.class_757.method_3192(class_757.java:750)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.CustomColors.getWorldSkyColor(CustomColors.java:1536)
	at net.minecraft.class_758.method_3210(class_758.java:91)
	at com.mamiyaotaru.voxelmap.Map.getSkyColor(Map.java:991)
	at com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:962)
	at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:695)
	at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:195)
	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:74)
	at net.minecraft.class_329.handler$zgd000$onRenderGameOverlay(class_329.java:1811)
	at net.minecraft.class_329.method_1753(class_329.java:441)

-- Affected level --
Details:
	All players: 4 total; [class_746['BattlemanMK2'/670453, l='ClientLevel', x=7464.10, y=67.00, z=8214.40], class_745['olinebeast'/631925, l='ClientLevel', x=7454.70, y=66.00, z=8204.01], class_745['JJ0823'/643069, l='ClientLevel', x=7453.08, y=66.00, z=8201.93], class_745['ChonNomJo'/669927, l='ClientLevel', x=7452.33, y=66.00, z=8228.52]]
	Chunk stats: Client Chunk Cache: 289, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,73,-176), Chunk: (at 0,4,0 in -14,-11; contains blocks -224,0,-176 to -209,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 70274 game time, 31462053 day time
	Server brand: Waterfall <- Tuinity
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:616)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:677)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1221324240 bytes (1164 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blue_endless_jankson: jankson +
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.5.6
		cmdkeybind: Command Macros 1.4.3-1.16
		craftpresence: CraftPresence 1.6.6
		fabric: Fabric API 0.15.1+build.380-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+0a55f37902
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.0+build.204
		inventoryprofiles: Inventory Profiles 0.4.2
		kyrptconfig: Kytpt Config 1.0.4-1.16
		lightoverlay: Light Overlay 5.4.0
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.14.5+build.30
		optifabric: Optifabric 1.1.0-beta2
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		voxelmap: VoxelMap 1.10.6
		worldedit: WorldEdit 7.2.0-beta-01+0eb9ac7
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre5
	OptiFine Build: 20200719-015630
	Render Distance Chunks: 30
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs_Vibrant_Shaders_v1.22_Extreme.zip
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce RTX 2080 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by BMK2** [comment]
The server I play on has a custom resource pack that seemed to be having issues with the Fabric API. After updating to their latest version, everything works fine.

**Comment by BMK2** [comment]
Reopening because turns out the issue wasn't fixed. Optifine starts the crash but it seems to be something VoxelMap is trying to read that optifine is changing and therefore crashing.

**Comment by Akuyi** [comment]
Hi,
I have exactly the same error with a server, which has a resource pack installed. 
On a server without a resource pack I can play without any problems with VoxelMap + OptiFine (1.16.2). But on the one with resource pack it always crashes with the same stack trace like mentioned above.

I currently try to figure out, what could be missing in the resource pack, but had no luck yet.

**Comment by Akuyi** [comment]
I just did some tests: When I edit the server entry in my server list to prompt if I want to download the resource pack and confirm this with "yes", everything works finde. 
When I reconnect with download resources automatically "enabled" it crashes. 

Could it be that the issue occures because the client reloads because of the server resource pack?

**Comment by pierrefasst** [comment]
Same here, just added ressource pack to my serv, without it it works fine, with it, crash everytime i try to connect on the server.

**Comment by pierrefasst** [comment]
I've found out that if you swap the mod loading and the base pack loading it works (for me)
Like bellow
![image](https://user-images.githubusercontent.com/61139431/97888214-2ff02a80-1d2b-11eb-8d64-bba845fb079a.png)

**Comment by Skulrag** [comment]
I've found out that if you swap the mod loading and the base pack loading it works (for me)
Like bellow
![image](https://user-images.githubusercontent.com/61139431/97888214-2ff02a80-1d2b-11eb-8d64-bba845fb079a.png)

**Comment by Xeravax** [comment]
I can still confirm this bug is happening on 1.17.1, the issue with our server is that the resource pack is **required** to join the server. (See: https://www.spigotmc.org/resources/%E2%9E%A2-thelab-minigame.26665/)

Whenever a user joins with both optifine and voxelmap, they crash.
